/**
 * Created by Scott Mackenzie on 12/07/17.
 */

export const services =
    [
        'ABR (P)',
        'Acute (A)',
        'Acute (P)',
        'ASU (A)',
        'Card Con (A)',
        'Cardiac (A)',
        'Cardiac (P)',
        'Flex',
        'Gastro (P)',
        'Gen Surg (A)',
        'Gynae (A)',
        'Neuro (A)',
        'Neuro (P)',
        'Obs (A)',
        'OH (A)',
        'OH (P)',
        'Onc (A)',
        'Onc (P)',
        'Ophth (A)',
        'Ophth (P)',
        'ORL (A)',
        'ORL (P)',
        'Ortho (A)',
        'Ortho (P)',
        'Ortho Acute',
        'Paed Surg (P)',
        'Pvt Gynae (A)',
        'Pvt Obs (A)',
        'Resp (A)',
        'Resp (P)',
        'TARPS',
        'Trans L (A)',
        'Trans R (A)',
        'Uro (A)',
        'Uro Acute',
        'Vas (A)',
        'SHUTDOWN',
        'Cardiology (A)',
        'Neuro Acute',
        'Ophth (LA)',
        'Gen Surg (LA)',
        'Plastics (P)',
        'Litho (A)',
        'UroGynae (A)',
        'Gynae Onc (A)',
        'Gynae-Fertility (A)',
        'Gynae-Adv Lap (A)',
        'Gynae-STOPS (A)',
        'Paed Ortho-Spines (P)',
        'Paed Ortho-Hands (P)',
        'Ophth-Cataract (A)',
        'Ophth-Corneal (A)',
        'Ophth-Glau (A)',
        'Ophth-Lasers (A)',
        'Ophth-M Ops (A)',
        'Ophth-OcPlas (A)',
        'Ophth-VR (A)',
        'Ophth-Squints (A)',
        'Gen Surg-Col (A)',
        'Gen Surg-HPB/UGI (A)',
        'Gen Surg-HNB&E (A)',
    ];

export const surgeons =
    [
        'Adam Bartlett',
        'Ai Ling Tan',
        'Alan Merry',
        'Alastair Hadlow',
        'Alex Ng',
        'Ali Khan',
        'Alison Corkill',
        'Allan Brown',
        'Amul Kumar Sibal',
        'Andrea Kelly',
        'Andrea Zarcovic',
        'Andrew Campbell',
        'Andrew Gavin',
        'Andrew Graydon',
        'Andrew Hill',
        'Andrew Holden',
        'Andrew Johnston',
        'Andrew Law',
        'Andrew Lienert',
        'Andrew Riley',
        'Andrew Williams',
        'Angus Don',
        'Angus Shao',
        'Anna Bashford Christie',
        'Anna Dawson',
        'Anna Lawrence',
        'Annalisa Meyer',
        'Anthony Beaven',
        'Antony Field',
        'Arend Merrie',
        'Arnold Bok',
        'Arthur Coverdale',
        'Ashish Taneja',
        'Astrid Budden',
        'Audrey Long',
        'Barry Lowe',
        'Ben Loveday',
        'Bill Baber',
        'Brian Joondeph',
        'Brian Sloan',
        'Bruce Twaddle',
        'Bryan Parry',
        'C. T. Anaesthetist',
        'Cameron Lewis',
        'Cara Wasywich',
        'Carl Muthu',
        'Carolyn Bilbrough',
        'Cass Byrnes',
        'Catherine McMurray',
        'Cecile Bergzoll',
        'Charles McGhee',
        'Chris Ellis',
        'Chris Fougere',
        'Christopher Furneaux',
        'Christopher Keall',
        'Christopher Occleshaw',
        'Christopher Sealey',
        'Cindy Farquhar',
        'Cindy Ooi',
        'Clairton De Souza',
        'Clare O\'Donnell',
        'Clayton Brown',
        'Colin Baird',
        'Colin Barber',
        'Colin Brown',
        'Craig Ball',
        'David Davies-Payne',
        'David Duncan',
        'David Haydock',
        'David Heaven',
        'David McNamara',
        'David Merrilees',
        'David Pendergrast',
        'David Perry',
        'David Squirrell',
        'David Vokes',
        'Dean Corbett',
        'Denys Court',
        'Deralie Flower',
        'Dereck Souter',
        'Dev Tandon',
        'Dipika Patel',
        'Douglas Scott',
        'Dr Andrew (Card) Martin',
        'Dr Andrew Martin',
        'Duncan Ferguson',
        'Duncan Wood',
        'Edward Mee',
        'Edwin Dorman',
        'Eletha Taylor',
        'Elizabeth Curr',
        'Elizabeth Edwards',
        'Elizabeth Rumball',
        'Emily Liu',
        'Emke Van Den Broek',
        'Emma Parry',
        'Erika Hunter',
        'Eva Fong',
        'Eva Hochstein',
        'Fiona Connell',
        'Generic A+ Links',
        'Generic Adult Emergency Med',
        'Generic Anaesthetist',
        'Generic Cardiac',
        'Generic Gastroenterology',
        'Generic General Medicine',
        'Generic Haemotology',
        'Generic Neurology',
        'Generic Neurosurgery',
        'Generic O.R.L.',
        'Generic Oral Health',
        'Generic Paed General',
        'Generic Paed Neurology',
        'Generic Paed Renal',
        'Generic Radiology',
        'Generic Renal',
        'Generic Respiratory',
        'Geoffrey Bye',
        'Gerard Willemsen',
        'Gillian Gibson',
        'Gowan Creamer',
        'Graeme Van Der Meer',
        'Graham Knottenbelt',
        'Grant Beban',
        'Gregory O\'Grady',
        'Guo Ling',
        'Guy Armstrong',
        'Haemish Crawford',
        'Hamish Sillars',
        'Helen Evans',
        'Helen Rawlinson',
        'Henrik Hack',
        'Hugh Blackley',
        'Hussain Patel',
        'Ian Bissett',
        'Ian Cathro',
        'Ian Civil',
        'Ian Mundy',
        'Indran Ramanathan',
        'Isaac Cranshaw',
        'Jacob Munro',
        'Jacob Twiss',
        'Jacques Marnewick',
        'James Hamill',
        'James Pemberton',
        'James Shaw',
        'Jamie Voss',
        'Jason Du',
        'Jenny McDougall',
        'Jens Lund',
        'Jeremy Stanley',
        'Jim Stewart',
        'Jith Somaratne',
        'Jo Koppens',
        'Jo Sims',
        'Joanna Doa',
        'Joanna Ngo',
        'Joel Bagadam',
        'John Artrip',
        'John Atkinson',
        'John Chaplin',
        'John Edwards',
        'John Ferguson',
        'John McCall',
        'John Ormiston',
        'John Papaconstantino',
        'John Stirling',
        'John Tuckey',
        'John Whittaker',
        'John Windsor',
        'John Wright',
        'Johnathan Wheeler',
        'Jon Bishop',
        'Jon Skinner',
        'Jonathan Masters',
        'Judith MacCormick',
        'Julian Hayes',
        'Julian Vyas',
        'Justin Mora',
        'Kamran Zargar',
        'Katherine McKenzie',
        'Kathleeya Stang-Veldhouse',
        'Kathryn Rice',
        'Katie Bach',
        'Katie Groom',
        'Kavin King',
        'Khaldoun Aweidah',
        'Khang Li Looi',
        'Kieran Davis',
        'Kirk Freeman',
        'Kirsten Finucane',
        'Kirsten McSweeney',
        'Krishanu Chaudhuri',
        'Lesley Salkeld',
        'Li Hsee',
        'Linda Batchelor',
        'Line List Oncology',
        'Lochie Teague',
        'Lois Eva',
        'Madhu Koya',
        'Maha Haddad',
        'Mahesh Harilall',
        'Mairi Wallace',
        'Manisha Narsinh',
        'Margaret Hood',
        'Marian Carter',
        'Mark Donaldson',
        'Mark Izzard',
        'Mark O\'Carroll',
        'Mark Webster',
        'Mark Winstanley',
        'Mark Wright',
        'Martgaret Harpham',
        'Martin Sowter',
        'Matthew Boyle',
        'Maurice Moriarty',
        'Michael Hanlon',
        'Michael Puttick',
        'Michael Rice',
        'Michel Neeff',
        'Michelle Harris',
        'Michelle Wise',
        'Michelle Wong',
        'Mischel Neill',
        'Monika Pradhan',
        'Monique Stein-De Laat',
        'Motohiko Yasutomi',
        'Murali Mahadevan',
        'Murray Beagley',
        'Murray Maccormick',
        'Nadeem Ahmad',
        'Nagham Al-Mozany',
        'Narme Deva',
        'Naveen Pillarisetti',
        'Neha Sood',
        'Neil Buddicom',
        'Neil Johnson',
        'Neil Pattison',
        'Neil Price',
        'Nichola Wilson',
        'Nicholas Evennett',
        'Nicholas Kang',
        'Nicholas Walker',
        'Nick Birchall',
        'Nick McIvor',
        'Nicola Broadbent',
        'Nigel Lever',
        'Nigel Wilson',
        'Nikki Mills',
        'Nir Fireman',
        'Nyree Cole',
        'Olivia Stuart',
        'Oncology Oncology',
        'Paget Milsom',
        'Parma Nand',
        'Patricia Ding',
        'Patrick Kaye',
        'Patrick Schweder',
        'Paul Macpherson',
        'Paul McCormack',
        'Paul Robinson',
        'Paul Rosser',
        'Paul Simcock',
        'Pauline Koopu',
        'Peter Alison',
        'Peter Hadden',
        'Peter Heppner',
        'Peter Johnston',
        'Peter Raudkivi',
        'Peter Robertson',
        'Peter Robinson',
        'Peter Ruygrok',
        'Peter Vanniasingham',
        'Philip Beattie',
        'Philip Morreau',
        'Philip Polkinghorne',
        'Prasanth Sadasivan Nair',
        'Rachael Barnes',
        'Rachael Niederer',
        'Radiology Anaesthetist',
        'Rajan Patel',
        'Ralph Stewart',
        'Renuka Bhat',
        'Richard Douglas',
        'Richard Hart',
        'Richard Nicol',
        'Rishi Ram',
        'Rizal Alwi',
        'Rob Aspoas',
        'Robin Erickson',
        'Rowan Collinson',
        'Rowan Valentine',
        'Russell Bourchier',
        'Russell Metcalfe',
        'Ruth Angell',
        'Salil Nair',
        'Saman Moeed',
        'Sanjay Pandanaboyana',
        'Sarah Welch',
        'Seif El-Jack',
        'Sergio Stefanelli',
        'Session Acute',
        'Shanu Subbiah',
        'Shaun Dai',
        'Shelley Reilly',
        'Shenton Chew',
        'Simon Chin',
        'Simon Kelly',
        'Simon Mills',
        'Simon Van Rij',
        'Sonya Bennett',
        'Stephanie Van Dijck',
        'Stephen Best',
        'Stephen Evans',
        'Stephen Merriless',
        'Stephen Mouat',
        'Stephen Munn',
        'Stewart Walsh',
        'Stuart Carroll',
        'Stuart Ferguson',
        'Stuart McCowan',
        'Sue Ormonde',
        'Sue Stott',
        'Sumit Samant',
        'Sunil Pillay',
        'Surgeon Cardiothoracic',
        'Surgeon Ob/Gyn Acute',
        'Surgeon Ophthalmic Acute',
        'Surgeon Orthopaedic',
        'Surgeon Orthopaedic Acute',
        'Surgeon Renal Transplant',
        'Surgeon Renal Vascular',
        'Surgeon Urology Acute',
        'Surgery Paed Acute',
        'Susan Brooks',
        'Sylvia Rosevear',
        'Tahira Malik',
        'Terri Bidwell',
        'Tim Glenie',
        'Tim Hornung',
        'Timothy Dawson',
        'Tin Lok Chiu',
        'Tom Butchard',
        'Tom Gentles',
        'Tony Baird',
        'Tony Lin',
        'Transplant Liver',
        'Trevor Coe',
        'Trevor Gray',
        'Troy Smithers',
        'Valeria Ivanova',
        'Vanessa Blair',
        'Venu Bhamidipaty',
        'Veronika Van Dijck',
        'Vipul Upadhyay',
        'Wanda Gaynor',
        'Wayne Jones',
        'William Harrison',
        'William Hecker',
        'William Wong',
        'Yaso Ramadas',
        'Yvonne Ng',
        'Zac Moaveni',
        'Fellow',
        'Registrar',
        'Consultant',
        'Not Specified',
    ];
