/**
 * Created by Scott Mackenzie on 12/07/17.
 */


export const pims = {
    'ABR (P)': {
        service: 'Audiology',
        type: 'Elective',
        age: 'Paediatric'
    },
    'Acute (A)': {
        service: 'Acute Surgery',
        type: 'Acute',
        age: 'Adult'
    },
    'Acute (P)': {
        service: 'Acute Surgery',
        type: 'Acute',
        age: 'Paediatric'
    },
    'ASU (A)': {
        service: 'General Surgery',
        type: 'Acute',
        age: 'Adult'
    },
    'Card Con (A)': {
        service: 'Adult Congenital Heart Disease [Surgical]',
        type: 'Acute',
        age: 'Adult'
    },
    'Cardiac (A)': {
        service: 'Cardiothoracic',
        type: 'Elective',
        age: 'Adult'
    },
    'Cardiac (P)': {
        service: 'Cardiothoracic',
        type: 'Elective',
        age: 'Paediatric'
    },
    'Flex': {
        service: 'Flex',
        type: '',
        age: ''
    },
    'Gastro (P)': {
        service: 'Paediatric Gastroenterology',
        type: 'Elective',
        age: 'Paediatric'
    },
    'Gen Surg (A)': {
        service: 'General Surgery',
        type: 'Elective',
        age: 'Adult'
    },
    'Gynae (A)': {
        service: 'Gynaecological',
        type: 'Elective',
        age: 'Adult'
    },
    'Neuro (A)': {
        service: 'Neurosurgery',
        type: 'Elective',
        age: 'Adult'
    },
    'Neuro (P)': {
        service: 'Neurosurgery',
        type: 'Elective',
        age: 'Paediatric'
    },
    'Obs (A)': {
        service: 'Maternity',
        type: 'Elective',
        age: 'Adult'
    },
    'OH (A)': {
        service: 'Oral Health',
        type: 'Elective',
        age: 'Adult'
    },
    'OH (P)': {
        service: 'Oral Health',
        type: 'Elective',
        age: 'Paediatric'
    },
    'Onc (A)': {
        service: 'Radiation Oncology',
        type: 'Elective',
        age: 'Adult'
    },
    'Onc (P)': {
        service: 'Medical Oncology',
        type: 'Elective',
        age: 'Paediatric'
    },
    'Ophth (A)': {
        service: 'Ophthalmology',
        type: 'Elective',
        age: 'Adult'
    },
    'Ophth (P)': {
        service: 'Ophthalmology',
        type: 'Elective',
        age: 'Paediatric'
    },
    'ORL (A)': {
        service: 'Otorhinolaryngology',
        type: 'Elective',
        age: 'Adult'
    },
    'ORL (P)': {
        service: 'Paediatric ENT',
        type: 'Elective',
        age: 'Paediatric'
    },
    'Ortho (A)': {
        service: 'Orthopaedics',
        type: 'Elective',
        age: 'Adult'
    },
    'Ortho (P)': {
        service: 'Paediatric Orthopaedics',
        type: 'Elective',
        age: 'Paediatric'
    },
    'Ortho Acute': {
        service: 'Orthopaedics',
        type: 'Acute',
        age: 'Adult'
    },
    'Paed Surg (P)': {
        service: 'Paediatric Surgery',
        type: 'Elective',
        age: 'Paediatric'
    },
    'Pvt Gynae (A)': {
        service: 'Gynaecological',
        type: 'Elective',
        age: 'Adult'
    },
    'Pvt Obs (A)': {
        service: 'Maternity',
        type: 'Elective',
        age: 'Adult'
    },
    'Resp (A)': {
        service: 'Respiratory',
        type: 'Elective',
        age: 'Adult'
    },
    'Resp (P)': {
        service: 'Paediatric Respiratory',
        type: 'Elective',
        age: 'Paediatric'
    },
    'TARPS': {
        service: 'Anaesthesia',
        type: 'Elective',
        age: 'Adult'
    },
    'TARPS (A)': {
        service: 'Anaesthesia',
        type: 'Elective',
        age: 'Adult'
    },
    'Trans L (A)': {
        service: 'Liver Transplant',
        type: 'Elective',
        age: 'Adult'
    },
    'Trans R (A)': {
        service: 'Renal Transplant',
        type: 'Elective',
        age: 'Adult'
    },
    'Uro (A)': {
        service: 'Urology',
        type: 'Elective',
        age: 'Adult'
    },
    'Uro Acute': {
        service: 'Urology',
        type: 'Acute',
        age: 'Adult'
    },
    'Vas (A)': {
        service: 'Vascular Service',
        type: 'Elective',
        age: 'Adult'
    },
    'SHUTDOWN': {
        service: 'SHUTDOWN',
        type: '',
        age: ''
    },
    'Cardiology (A)': {
        service: 'Cardiology',
        type: 'Elective',
        age: 'Adult'
    },
    'Neuro Acute': {
        service: 'Neurosurgery',
        type: 'Acute',
        age: 'Adult'
    },
    'Ophth (LA)': {
        service: 'Ophthalmology',
        type: 'Elective',
        age: 'Adult'
    },
    'Gen Surg (LA)': {
        service: 'General Surgery',
        type: 'Elective',
        age: 'Adult'
    },
    'Plastics (P)': {
        service: 'Paediatric ENT',
        type: 'Elective',
        age: 'Paediatric'
    },
    'Litho (A)': {
        service: 'Urology',
        type: 'Elective',
        age: 'Adult'
    },
    'UroGynae (A)': {
        service: 'Gynaecological',
        type: 'Elective',
        age: 'Adult'
    },
    'Gynae Onc (A)': {
        service: 'Gynaecological',
        type: 'Elective',
        age: 'Adult'
    },
    'Gynae-Fertility (A)': {
        service: 'Gynaecological',
        type: 'Elective',
        age: 'Adult'
    },
    'Gynae-Adv Lap (A)': {
        service: 'Gynaecological',
        type: 'Elective',
        age: 'Adult'
    },
    'Gynae-STOPS (A)': {
        service: 'Gynaecological',
        type: 'Elective',
        age: 'Adult'
    },
    'Paed Ortho-Spines (P)': {
        service: 'Paediatric Orthopaedics',
        type: 'Elective',
        age: 'Paediatric'
    },
    'Paed Ortho-Hands (P)': {
        service: 'Paediatric Orthopaedics',
        type: 'Elective',
        age: 'Paediatric'
    },
    'Ophth-Cataract (A)': {
        service: 'Ophthalmology',
        type: 'Elective',
        age: 'Adult'
    },
    'Ophth-Corneal (A)': {
        service: 'Ophthalmology',
        type: 'Elective',
        age: 'Adult'
    },
    'Ophth-Glau (A)': {
        service: 'Ophthalmology',
        type: 'Elective',
        age: 'Adult'
    },
    'Ophth-Lasers (A)': {
        service: 'Ophthalmology',
        type: 'Elective',
        age: 'Adult'
    },
    'Ophth-M Ops (A)': {
        service: 'Ophthalmology',
        type: 'Elective',
        age: 'Adult'
    },
    'Ophth-OcPlas (A)': {
        service: 'Ophthalmology',
        type: 'Elective',
        age: 'Adult'
    },
    'Ophth-VR (A)': {
        service: 'Ophthalmology',
        type: 'Elective',
        age: 'Adult'
    },
    'Ophth-Squints (A)': {
        service: 'Ophthalmology',
        type: 'Elective',
        age: 'Adult'
    },
    'Gen Surg-Col (A)': {
        service: 'General Surgery',
        type: 'Elective',
        age: 'Adult'
    },
    'Gen Surg-HPB/UGI (A)': {
        service: 'General Surgery',
        type: 'Elective',
        age: 'Adult'
    },
    'Gen Surg-HNB&E (A)': {
        service: 'General Surgery',
        type: 'Elective',
        age: 'Adult'
    },
    'ORL-Laryng (A)': {
        service: 'Otorhinolaryngology',
        type: 'Elective',
        age: 'Adult'
    },
    'ORL-Oto (A)': {
        service: 'Otorhinolaryngology',
        type: 'Elective',
        age: 'Adult'
    },
    'ORL-H&N (A)': {
        service: 'Otorhinolaryngology',
        type: 'Elective',
        age: 'Adult'
    },
    'ORL-Rhino (A)': {
        service: 'Otorhinolaryngology',
        type: 'Elective',
        age: 'Adult'
    },

}


export const services =
  [
    'ABR (P)',
    'Acute (A)',
    'Acute (P)',
    'ASU (A)',
    'Card Con (A)',
    'Cardiac (A)',
    'Cardiac (P)',
    'Flex',
    'Gastro (P)',
    'Gen Surg (A)',
    'Gynae (A)',
    'Neuro (A)',
    'Neuro (P)',
    'Obs (A)',
    'OH (A)',
    'OH (P)',
    'Onc (A)',
    'Onc (P)',
    'Ophth (A)',
    'Ophth (P)',
    'ORL (A)',
    'ORL (P)',
      'ORL-Laryng (A)',
      'ORL-Oto (A)',
      'ORL-H&N (A)',
      'ORL-Rhino (A)',
    'Ortho (A)',
    'Ortho (P)',
    'Ortho Acute',
    'Paed Surg (P)',
    'Pvt Gynae (A)',
    'Pvt Obs (A)',
    'Resp (A)',
    'Resp (P)',
    'TARPS',
    'Trans L (A)',
    'Trans R (A)',
    'Uro (A)',
    'Uro Acute',
    'Vas (A)',
    'SHUTDOWN',
    'Cardiology (A)',
    'Neuro Acute',
    'Ophth (LA)',
    'Gen Surg (LA)',
    'Plastics (P)',
    'Litho (A)',
    'UroGynae (A)',
    'Gynae Onc (A)',
    'Gynae-Fertility (A)',
    'Gynae-Adv Lap (A)',
    'Gynae-STOPS (A)',
    'Paed Ortho-Spines (P)',
    'Paed Ortho-Hands (P)',
    'Ophth-Cataract (A)',
    'Ophth-Corneal (A)',
    'Ophth-Glau (A)',
    'Ophth-Lasers (A)',
    'Ophth-M Ops (A)',
    'Ophth-OcPlas (A)',
    'Ophth-VR (A)',
    'Ophth-Squints (A)',
    'Gen Surg-Col (A)',
    'Gen Surg-HPB/UGI (A)',
    'Gen Surg-HNB&E (A)',
  ];

export const surgeons =
  [
      'Bartlett, Adam',
      'Merry, Alan',
      'Hadlow, Alastair',
      'Ng, Alex',
      'Khan, Ali',
      'Corkill, Alison',
      'Brown, Allan',
      'Kelly, Andrea',
      'Zarcovic, Andrea',
      'Campbell, Andrew',
      'Gavin, Andrew',
      'Graydon, Andrew',
      'Hill, Andrew',
      'Holden, Andrew',
      'Johnston, Andrew',
      'Law, Andrew',
      'Lienert, Andrew',
      'Riley, Andrew',
      'Williams, Andrew',
      'Don, Angus',
      'Shao, Angus',
      'Dawson, Anna',
      'Lawrence, Anna',
      'Meyer, Annalisa',
      'Beaven, Anthony',
      'Field, Antony',
      'Merrie, Arend',
      'Bok, Arnold',
      'Coverdale, Arthur',
      'Taneja, Ashish',
      'Budden, Astrid',
      'Long, Audrey',
      'Lowe, Barry',
      'Loveday, Ben',
      'Baber, Bill',
      'Joondeph, Brian',
      'Sloan, Brian',
      'Twaddle, Bruce',
      'Parry, Bryan',
      'Lewis, Cameron',
      'Wasywich, Cara',
      'Muthu, Carl',
      'Bilbrough, Carolyn',
      'Byrnes, Cass',
      'McMurray, Catherine',
      'Bergzoll, Cecile',
      'McGhee, Charles',
      'Ellis, Chris',
      'Fougere, Chris',
      'Furneaux, Christopher',
      'Keall, Christopher',
      'Occleshaw, Christopher',
      'Sealey, Christopher',
      'Farquhar, Cindy',
      'Ooi, Cindy',
      'Souza, Clairton De',
      'O\'Donnell, Clare',
      'Brown, Clayton',
      'Baird, Colin',
      'Barber, Colin',
      'Brown, Colin',
      'Ball, Craig',
      'Davies-Payne, David',
      'Duncan, David',
      'Haydock, David',
      'Heaven, David',
      'McNamara, David',
      'Merrilees, David',
      'Pendergrast, David',
      'Perry, David',
      'Squirrell, David',
      'Vokes, David',
      'Corbett, Dean',
      'Court, Denys',
      'Flower, Deralie',
      'Souter, Dereck',
      'Tandon, Dev',
      'Patel, Dipika',
      'Scott, Douglas',
      'Ferguson, Duncan',
      'Wood, Duncan',
      'Mee, Edward',
      'Dorman, Edwin',
      'Taylor, Eletha',
      'Curr, Elizabeth',
      'Edwards, Elizabeth',
      'Rumball, Elizabeth',
      'Liu, Emily',
      'Parry, Emma',
      'Hunter, Erika',
      'Fong, Eva',
      'Hochstein, Eva',
      'Connell, Fiona',
      'Links, Generic A+',
      'Bye, Geoffrey',
      'Willemsen, Gerard',
      'Gibson, Gillian',
      'Creamer, Gowan',
      'Meer, Graeme Van Der',
      'Knottenbelt, Graham',
      'Beban, Grant',
      'O\'Grady, Gregory',
      'Ling, Guo',
      'Armstrong, Guy',
      'Crawford, Haemish',
      'Sillars, Hamish',
      'Evans, Helen',
      'Rawlinson, Helen',
      'Hack, Henrik',
      'Blackley, Hugh',
      'Patel, Hussain',
      'Bissett, Ian',
      'Cathro, Ian',
      'Civil, Ian',
      'Mundy, Ian',
      'Ramanathan, Indran',
      'Cranshaw, Isaac',
      'Munro, Jacob',
      'Twiss, Jacob',
      'Marnewick, Jacques',
      'Hamill, James',
      'Pemberton, James',
      'Shaw, James',
      'Voss, Jamie',
      'Du, Jason',
      'McDougall, Jenny',
      'Lund, Jens',
      'Stanley, Jeremy',
      'Stewart, Jim',
      'Somaratne, Jith',
      'Koppens, Jo',
      'Sims, Jo',
      'Doa, Joanna',
      'Ngo, Joanna',
      'Bagadam, Joel',
      'Artrip, John',
      'Atkinson, John',
      'Chaplin, John',
      'Edwards, John',
      'Ferguson, John',
      'McCall, John',
      'Ormiston, John',
      'Papaconstantino, John',
      'Stirling, John',
      'Tuckey, John',
      'Whittaker, John',
      'Windsor, John',
      'Wright, John',
      'Wheeler, Johnathan',
      'Bishop, Jon',
      'Skinner, Jon',
      'Masters, Jonathan',
      'MacCormick, Judith',
      'Hayes, Julian',
      'Vyas, Julian',
      'Mora, Justin',
      'Zargar, Kamran',
      'McKenzie, Katherine',
      'Rice, Kathryn',
      'Bach, Katie',
      'Groom, Katie',
      'King, Kavin',
      'Aweidah, Khaldoun',
      'Looi, Khang Li',
      'Davis, Kieran',
      'Freeman, Kirk',
      'Finucane, Kirsten',
      'McSweeney, Kirsten',
      'Chaudhuri, Krishanu',
      'Salkeld, Lesley',
      'Hsee, Li',
      'Batchelor, Linda',
      'Oncology, Line List',
      'Teague, Lochie',
      'Eva, Lois',
      'Koya, Madhu',
      'Haddad, Maha',
      'Harilall, Mahesh',
      'Wallace, Mairi',
      'Narsinh, Manisha',
      'Hood, Margaret',
      'Carter, Marian',
      'Donaldson, Mark',
      'Izzard, Mark',
      'O\'Carroll, Mark',
      'Webster, Mark',
      'Winstanley, Mark',
      'Wright, Mark',
      'Harpham, Martgaret',
      'Sowter, Martin',
      'Boyle, Matthew',
      'Moriarty, Maurice',
      'Hanlon, Michael',
      'Puttick, Michael',
      'Rice, Michael',
      'Neeff, Michel',
      'Harris, Michelle',
      'Wise, Michelle',
      'Wong, Michelle',
      'Neill, Mischel',
      'Pradhan, Monika',
      'Laat, Monique Stein-De',
      'Yasutomi, Motohiko',
      'Mahadevan, Murali',
      'Beagley, Murray',
      'Maccormick, Murray',
      'Ahmad, Nadeem',
      'Al-Mozany, Nagham',
      'Deva, Narme',
      'Pillarisetti, Naveen',
      'Sood, Neha',
      'Buddicom, Neil',
      'Johnson, Neil',
      'Pattison, Neil',
      'Price, Neil',
      'Wilson, Nichola',
      'Evennett, Nicholas',
      'Kang, Nicholas',
      'Walker, Nicholas',
      'Birchall, Nick',
      'McIvor, Nick',
      'Broadbent, Nicola',
      'Lever, Nigel',
      'Wilson, Nigel',
      'Mills, Nikki',
      'Fireman, Nir',
      'Cole, Nyree',
      'Stuart, Olivia',
      'Milsom, Paget',
      'Nand, Parma',
      'Ding, Patricia',
      'Kaye, Patrick',
      'Schweder, Patrick',
      'Macpherson, Paul',
      'McCormack, Paul',
      'Robinson, Paul',
      'Rosser, Paul',
      'Simcock, Paul',
      'Koopu, Pauline',
      'Alison, Peter',
      'Hadden, Peter',
      'Heppner, Peter',
      'Johnston, Peter',
      'Raudkivi, Peter',
      'Robertson, Peter',
      'Robinson, Peter',
      'Ruygrok, Peter',
      'Vanniasingham, Peter',
      'Beattie, Philip',
      'Morreau, Philip',
      'Polkinghorne, Philip',
      'Nair, Prasanth Sadasivan',
      'Barnes, Rachael',
      'Niederer, Rachael',
      'Patel, Rajan',
      'Stewart, Ralph',
      'Bhat, Renuka',
      'Douglas, Richard',
      'Hart, Richard',
      'Nicol, Richard',
      'Ram, Rishi',
      'Alwi, Rizal',
      'Aspoas, Rob',
      'Erickson, Robin',
      'Collinson, Rowan',
      'Valentine, Rowan',
      'Bourchier, Russell',
      'Metcalfe, Russell',
      'Angell, Ruth',
      'Nair, Salil',
      'Moeed, Saman',
      'Pandanaboyana, Sanjay',
      'Welch, Sarah',
      'El-Jack, Seif',
      'Stefanelli, Sergio',
      'Subbiah, Shanu',
      'Dai, Shaun',
      'Reilly, Shelley',
      'Chew, Shenton',
      'Chin, Simon',
      'Kelly, Simon',
      'Mills, Simon',
      'Rij, Simon Van',
      'Bennett, Sonya',
      'Dijck, Stephanie Van',
      'Best, Stephen',
      'Evans, Stephen',
      'Merriless, Stephen',
      'Mouat, Stephen',
      'Munn, Stephen',
      'Walsh, Stewart',
      'Carroll, Stuart',
      'Ferguson, Stuart',
      'McCowan, Stuart',
      'Ormonde, Sue',
      'Stott, Sue',
      'Samant, Sumit',
      'Pillay, Sunil',
      'Brooks, Susan',
      'Rosevear, Sylvia',
      'Malik, Tahira',
      'Bidwell, Terri',
      'Glenie, Tim',
      'Hornung, Tim',
      'Dawson, Timothy',
      'Chiu, Tin Lok',
      'Butchard, Tom',
      'Gentles, Tom',
      'Baird, Tony',
      'Lin, Tony',
      'Liver Transplant',
      'Coe, Trevor',
      'Gray, Trevor',
      'Smithers, Troy',
      'Ivanova, Valeria',
      'Blair, Vanessa',
      'Bhamidipaty, Venu',
      'Dijck, Veronika Van',
      'Upadhyay, Vipul',
      'Gaynor, Wanda',
      'Jones, Wayne',
      'Harrison, William',
      'Hecker, William',
      'Wong, William',
      'Ramadas, Yaso',
      'Ng, Yvonne',
      'Moaveni, Zac',
      'Stang-Veldhouse, Kathleeya',
      'Generic Adult Emergency Med',
      'Generic Anaesthetist',
      'Generic Cardiac',
      'Generic Gastroenterology',
      'Generic General Medicine',
      'Generic Haemotology',
      'Generic Neurology',
      'Generic Neurosurgery',
      'Generic O.R.L.',
      'Generic Oral Health',
      'Generic Paed General',
      'Generic Paed Neurology',
      'Generic Paed Renal',
      'Generic Radiology',
      'Generic Renal',
      'Generic Respiratory',
      'Van Den Broek, Emke',
      'Christie, Anna Bashford',
      'Kumar Sibal, Amul',
      'Tan, Ai Ling',
      'Fellow',
      'Registrar',
      'Consultant',
      'Not Specified'
  ];
